### ISSUE TITLE
Violation of GPL

### ISSUE THREAD

**Issue by uglide** [plamendp/redis-navigator-tracker#9]
Hello Plamen

It's nice to see that you have added couple useful features to RedisDesktopManager and even published it to Mac Store as your software but you are violating GPLv3 licence by not publishing the source code of your RediNav software. Please publish source code of your software on Github or any other way till 1 October 2018 or I will submit the complaint to Apple Inc.

Best Regards!

**Comment by plamendp** [comment]
Published Source download link at https://www.redinav.com  (next to Privacy policy link at the bottom).
It was and is also available at welcome UI in the binary App too.

![selection_458](https://user-images.githubusercontent.com/2060234/46168809-28cfd600-c2a2-11e8-8677-1bd4d797bed4.png)

![selection_459](https://user-images.githubusercontent.com/2060234/46168859-4604a480-c2a2-11e8-831e-fc9e164f5a15.png)

And here is the link itself:  https://www.redinav.com/wp-content/uploads/2018/09/redinav-src.tar.gz

**Comment by uglide** [comment]
@plamendp thanks!

Redis Desktop Manager is covered by **GPLv3** not **L**GPLv3. Please fix text in your app welcome screen.
